nameOverride: argo-rollouts

installCRDs: true

controller:
  tolerations:
    - key: group
      operator: Equal
      value: operation
      effect: NoSchedule

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: group
                operator: In
                values:
                  - operation
