nameOverride: prometheus-adapter

prometheus:
  url: "http://prometheus-operator-prometheus.addon-prometheus.svc.cluster.local"
  port: 9090

rules:
  default: true
  custom:
    - seriesQuery: 'container_network_receive_bytes_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: { resource: "namespace" }
          pod: { resource: "pod" }
      name:
        matches: "^(.*)_total"
        as: "${1}"
      metricsQuery: "sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)"

# podAnnotations:
#   cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

tolerations:
  - key: group
    operator: Equal
    value: monitoring
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: group
              operator: In
              values:
                - monitoring
